main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('daftar-kegiatan/', views.daftar, name="daftar"),
    path('tambah-kegiatan/', views.tambah, name="tambah"),
    path('tambah-peserta/', views.tambah_peserta, name='karepmu'),
]

storyenam/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime, date

# Create your models here.
class Kegiatan(models.Model):
    kegiatan = models.CharField(max_length = 100)

    def __str__(self):
        return "{}".format(self.kegiatan)

    
class Anggota(models.Model):
    kegiatan = models.ForeignKey(Kegiatan, on_delete=models.CASCADE, related_name='peserta')
    anggota = models.CharField(max_length=100)

    def __str__(self):
        return "{:s}".format(self.anggota)

main/forms.py
from django.forms import ModelForm
from .models import Anggota, Kegiatan

class TambahPesertaForm(ModelForm):
    class Meta:
        model = Anggota
        fields = '__all__'


class TambahKegiatanForm(ModelForm):
    class Meta:
        model = Kegiatan
        fields = '__all__'

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .forms import TambahKegiatanForm, TambahPesertaForm
from .models import Kegiatan, Anggota

def home(request):
    return render(request, 'main/home.html')

def daftar(request):
    form = TambahPesertaForm(request.POST or None)
    response = {
        "kegiatans" : Kegiatan.objects.all(),
        "form_peserta" : TambahPesertaForm,
    }

    return render(request, 'main/kegiatan.html', response)


def tambah_peserta(request, id=None):
    form = TambahPesertaForm(request.POST or None)
    kegiatan = Kegiatan.objects.get(id=id)

    if (request.method == 'POST'):
        nama_anggota = form["anggota"].value()
        anggota = Anggota(kegiatan=kegiatan, anggota=nama_anggota)
        anggota.save()
    return HttpResponseRedirect('/daftar-kegiatan/')

def tambah(request):
    form = TambahKegiatanForm(request.POST or None)
    response = {
        "form_kegiatan" : TambahKegiatanForm,
    }
    if (form.is_valid() and request.method == 'POST'):
        form.save()
        return HttpResponseRedirect('/daftar-kegiatan/')
    return render(request, 'main/tambah.html', response)

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story 6</title>
{% endblock meta %}

{% block content %}
  <div class="container-fluid" style="background-color: aliceblue ;background-size: cover; height: 100vh; text-align: center;">
    <h1 style="color: yellowgreen; padding-top: 200px; font-weight: 800; font-size: 70px;">Kegiatan Story 6</h1>
    <a href="{% url 'main:daftar' %}" class="btn btn-secondary btn-lg" role="button" style="margin-top: 50px;">IKUT!</a>
  </div>
{% endblock content %}

main/templates/main/kegiatan.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Kegiatan</title>
{% endblock meta %}

{% block content %}
    <div class="kegiatan-card">
        <h2>{{ kegiatan.kegiatan }}</h2>
        
        <!-- Daftar Nama Peserta -->
        <p>Peserta: </p>
        {% if kegiatan.peserta.all|length > 0 %}
        {% for nama in kegiatan.peserta.all %}
            <div class="nama-peserta"><p>{{ nama }}</p></div>
        {% endfor %}

        {% else %}
            <div class="nama-peserta"><p>--Tidak ada peserta--</p></div>
        {% endif %}
        
        <!-- Form daftar peserta kegiatan -->
        <div class="">
            <form class="tambah-peserta" action="{% url 'main:daftar' %}" method="POST">
                {% csrf_token %}
                {{ form_peserta.anggota }}
        
                <a ><button type="submit" class="button">Tambah Peserta</button></a>
            </form>
        </div>
    </div>
    <a href="{% url 'main:tambah' %}" class="btn btn-secondary btn-lg" role="button" style="margin-top: 50px;">TAMBAH KEGIATAN</a>
{% endblock content %}

main/templates/main/tambah.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Pendaftaran</title>
{% endblock meta %}

{% block content %}
    <div class="container-fluid" style="background-color: aliceblue ;background-size: cover; height: 100vh; text-align: center;">
        <!-- Daftar Kegiatan -->
            <div class="kegiatan-card">
                <h2>Tambah Kegiatan Baru</h2>
        <!-- Form daftar peserta kegiatan -->
            <div class="">
                <form class="tambah-peserta" action="" method="POST">
                {% csrf_token %}
                {{ form_kegiatan.kegiatan }}
        
                <a ><button type="submit" class="button">Tambah Kegiatan</button></a>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="icon" href="https://instagram.fjog3-1.fna.fbcdn.net/v/t51.2885-15/e35/121022302_2633969000248438_2639764292890891293_n.jpg?_nc_ht=instagram.fjog3-1.fna.fbcdn.net&_nc_cat=110&_nc_ohc=PI9VnlmLx9UAX9-xhLi&_nc_tp=18&oh=f325b97d799b14c6d768440705d538b2&oe=5FAAF85A">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>

</html>